#DATA SCIENCE PROJECT FOR MTN COTE-D’IVOIRE
Infrastructure Upgrade Strategy Analysis and Recommendation

###General Information
MTN Cote d’Ivoire/Ivory Coast requires to upgrade their infrastructure for better user experience of it’s subscribers. They have shared their dataset to myself as a data scientist for analysis and advice on strategy to undertake.

###Data

####Datassets below provided

#####cells_geo_description.xlsx [https://drive.google.com/a/moringaschool.com/file/d/1-rIM5ihDu79RaH7rAs-d-7SQSAQhrY9N/view?usp=sharing]
#####cells_geo.csv [https://drive.google.com/a/moringaschool.com/file/d/1ABZux280OjL3yWcOn8BDA_f5QsyO0QPU/view?usp=sharing]
#####CDR_description.xlsx [https://drive.google.com/open?id=1cVoNXl25IO5-_yQk97ThdeqhE6yw8YTD]
#####CDR 20120507 [http://bit.ly/TelecomDataset1]
#####CDR 20120508 [http://bit.ly/TelecomDataset2]
#####CDR 20120509 [http://bit.ly/TelecomDataset3]

#1.Importing libraries

In [3]:
#Importing pandas for data manipulation
import pandas as pd
import numpy as np

#1.1.Loading data in our dataframes

In [4]:
#Loading the cells geo data set
dt1 = '/content/cells_geo.csv'
df1= pd.read_csv(dt1,delimiter=';', header =1, names = ['City','Status','Locality','Geographical_Zone','Zone_Name','Longitude','Latitude','Region','Area','Cell_ID','Site_ID'])
df1

          City      Status   Locality  ...          Area     Cell_ID     Site_ID
1       ADJAME  In Service    ABIDJAN  ...           NaN  1502501d78  0bb492ef17
2       ADJAME  In Service    ABIDJAN  ...           NaN  0c2e182a0c  0bb492ef17
3      ASSINIE  In Service  INTERIEUR  ...           NaN  69bdfc69fd  8a1e6ce31f
4      ASSINIE  In Service  INTERIEUR  ...           NaN  7a1029d2ab  8a1e6ce31f
5      ASSINIE  In Service  INTERIEUR  ...           NaN  0b4f56438f  8a1e6ce31f
...        ...         ...        ...  ...           ...         ...         ...
3969  ZUENOULA  In Service  INTERIEUR  ...  CENTRE NORTH  1cfc2d7ab1  f91ed8d2e9
3970  ZUENOULA  In Service  INTERIEUR  ...  CENTRE NORTH  3ae1708153  f91ed8d2e9
3971  ZUENOULA  In Service  INTERIEUR  ...  CENTRE NORTH  cb71f8a29c  61bee9c70c
3972  ZUENOULA  In Service  INTERIEUR  ...  CENTRE NORTH  d4a6a0b645  61bee9c70c
3973  ZUENOULA  In Service  INTERIEUR  ...  CENTRE NORTH  f9f3e42589  61bee9c70c

[3973 rows x 11 columns]

In [5]:
#Loading the cells geo description dataset
dt2 = '/content/cells_geo_description.xlsx'
df2= pd.read_excel(dt2)
df2

     Column name                                        Description  Format
0         VILLES                                               City  String
1         STATUS                                  In Service or not  String
2   LOCALISATION                                  in ABIDJAN or not  String
3     DECOUPZONE                                  Geographical Zone  String
4       ZONENAME                                       Name of Zone  String
5      LONGITUDE                                          Longitude   Float
6       LATITUDE                                           Latitude   Float
7         REGION                                             Region  String
8           AREA                                               Area  String
9        CELL_ID                                     ID of the cell  String
10     SITE_CODE  Site (there are several cells per site, severa...  String

In [6]:
#Loading the CDR description dataset
dt3 = '/content/CDR_description.xlsx'
df3= pd.read_excel(dt3)
df3

       Column name                                        Description   Format
0          PRODUCT                                       Voice or SMS   String
1            VALUE                                      Billing price  Integer
2        DATE_TIME               Time in format yyyy-MM-dd hh:mm:ss.0   String
3     CELL_ON_SITE  Which cell in the site was used (not needed here)  Integer
4  DW_A_NUMBER_INT  Anonymized phone number of the person for whic...   String
5  DW_B_NUMBER_INT        Anonymized phone number of the counterparty   String
6        COUNTRY_A                  Country of party A (useless here)   String
7        COUNTRY_B                  Country of party B (useless here)   String
8          CELL_ID                                     ID of the cell   String
9          SITE_ID                                     ID of the SITE   String

In [7]:
#Loading Moringa dataset 1
dt4 ='/content/MoringaSchool_CB_CDR_20120507.csv'
df4 = pd.read_csv(dt4,header =0, names = ['PRODUCT','VALUE','DATE_TIME','CELL_ON_SITE','DW_A_NUMBER','DW_B_NUMBER','COUNTRTY_A','COUNTRY_B','CELL_ID','SITE_ID'])
df4

        PRODUCT  VALUE              DATE_TIME  ... COUNTRY_B     CELL_ID     SITE_ID
0         Voice     53  2012-05-07 06:48:00.0  ...     19e2e  c258ffa6f0  f72cd95f00
1         Voice     63  2012-05-07 06:48:00.0  ...     19e2e  9c4c7ceb92  a07e8af2b4
2         Voice      0  2012-05-07 06:48:00.0  ...     19e2e  e38ca1003e  947b96a9ae
3         Voice      0  2012-05-07 06:48:00.0  ...     19e2e  73ebcb5c68  f078b9eea8
4         Voice    210  2012-05-07 06:48:00.0  ...     19e2e  96593c24dd  334fdb9912
...         ...    ...                    ...  ...       ...         ...         ...
3052915   Voice     70  2012-05-07 10:21:46.0  ...     19e2e  f7f7fc459b  505e321af5
3052916   Voice      0  2012-05-07 10:21:46.0  ...     19e2e  d880811c1a  f24a0f63fa
3052917   Voice    240  2012-05-07 10:21:46.0  ...     19e2e  da874d6b6d  e0cf6b8069
3052918   Voice     66  2012-05-07 10:21:46.0  ...     19e2e  d3a0b68ba8  969b8d0e39
3052919   Voice     24                  2012-  ...       NaN         NaN         NaN

[3052920 rows x 10 columns]

In [8]:
#Loading Moringa dataset2
dt5 = '/content/MoringaSchool_CB_CDR_20120508.csv'
df5 = pd.read_csv(dt5,header =0, names = ['PRODUCT','VALUE','DATE_TIME','CELL_ON_SITE','DW_A_NUMBER','DW_B_NUMBER','COUNTRTY_A','COUNTRY_B','CELL_ID','SITE_ID'])
df5

         PRODUCT  VALUE  ...     CELL_ID     SITE_ID
0            sms      0  ...  +854AcBQT2  +854AcBQT2
1          Voice      0  ...  +854AcBQT2  +854AcBQT2
2            sms      0  ...  +laSrk7g6q  +laSrk7g6q
3          Voice     37  ...  /xvRrCVKoQ  /xvRrCVKoQ
4            sms     25  ...  +bO+qkSonO  +bO+qkSonO
...          ...    ...  ...         ...         ...
19606107     sms      0  ...  z34dRyOVua  z34dRyOVua
19606108     sms      0  ...  zbVRn1hiwe  zbVRn1hiwe
19606109    data      0  ...  zIzAzjMShv  zIzAzjMShv
19606110   Voice    101  ...  zqHx55Evcc  zqHx55Evcc
19606111     sms      0  ...  zqHx55Evcc  zqHx55Evcc

[19606112 rows x 10 columns]

In [9]:
#Loading Moringa dataset3
dt6 = '/content/MoringaSchool_CB_CDR_20120509.csv'
df6 = pd.read_csv(dt6,header =0, names = ['PRODUCT','VALUE','DATE_TIME','CELL_ON_SITE','DW_A_NUMBER','DW_B_NUMBER','COUNTRTY_A','COUNTRY_B','CELL_ID','SITE_ID'])
df6

        PRODUCT  VALUE              DATE_TIME  ... COUNTRY_B     CELL_ID     SITE_ID
0         Voice     61  2012-05-08 23:01:28.0  ...     19e2e  +38u2u/rfx  +38u2u/rfx
1           sms      0  2012-05-08 23:01:31.0  ...     19e2e  +Fs4mTvdKx  +Fs4mTvdKx
2         Voice     10  2012-05-08 23:02:59.0  ...     19e2e  +ZaaZozy/+  +ZaaZozy/+
3           sms      0  2012-05-08 23:03:04.0  ...     19e2e  +cNeJzsTp3  +cNeJzsTp3
4         Voice     22  2012-05-08 23:03:16.0  ...     19e2e  /eeMklgyJA  /eeMklgyJA
...         ...    ...                    ...  ...       ...         ...         ...
3686482     sms      0  2012-05-09 10:52:59.0  ...     19e2e  350ba627d1  71e0db3bff
3686483     sms      0  2012-05-09 10:52:59.0  ...     19e2e  3516a6737a  2401a3c831
3686484     sms      0  2012-05-09 10:52:59.0  ...     19e2e  104e2f7154  165d822fcb
3686485     sms      0  2012-05-09 10:52:59.0  ...     19e2e  8c02a28508  f9c46f6693
3686486     sms      0  2012-05-09 10:52:59.0  ...       NaN         NaN         NaN

[3686487 rows x 10 columns]

#1.2.Data Exploration.

#1.2.1.Finding unique values in cells geo

In [ ]:
#Finding unique values in the columns
print(df1.City.unique())
#unique values in status column
print(df1.Status.unique())
#unique values in locality column
print(df1.Locality.unique())
#Unique values in geographical zone column
print(df1.Geographical_Zone.unique())
#Unique values in zone name column
print(df1.Zone_Name.unique())
#unique value in longitude column
print(df1.Longitude.unique())
#unique values in latitude column
print(df1.Latitude.unique())
#unique values in Regions column
print(df1.Region.unique())
#unique values in area column
print(df1.Area.unique())
#unique values in cell id column
print(df1.Cell_ID.unique())
#unique values in site id column
print(df1.Site_ID.unique())

['ADJAME' 'ASSINIE' 'KRIKOREA' 'ABOBO' 'BINGERVILLE' 'PLATEAU' 'DALOA'
 'ABENGOUROU' 'ATTECOUBE' 'ABOISSO COMOE' 'ABOISSO' 'BONGOUANOU'
 'ABONGOUA' 'ABOUDEKOUASSIKRO' 'ABRONAMOUE' 'YOPOUGON' 'ADAOU' 'ADDAH'
 'ADEBEM' 'ADIAKE' 'ADJAMENE' 'PORT-BOUET' 'ADZOPE' 'AFFERY' 'COCODY'
 'AGBOVILLE' 'AGNIBILEKRO' 'AGONDA' 'AGOU' 'MARCORY' 'AHIZABRO' 'AHOUANOU'
 'BOUAKE' 'AKOBOISSUE' 'AKOUPE' 'AKOUYAKRO' 'AKRADJO' 'KOUMASSI' 'ALEPE'
 'ALERIA' 'BAMORO' 'ALLOKOI' 'ANANDA' 'ANDO' 'ANDOKOKRENOU' 'ANIANSUE'
 'ANOUMABA' 'ANYAMA' 'AOUNIANFOUTOU' 'APPOISSO' 'ARRAH' 'ASSIKOI'
 'ASSUEFRY' 'ATTIGUEHI' 'ATTINGUIE' 'ATTROBROU' 'AYAME' 'AYAPRIKRO'
 'AZAGUIE' 'BACANDA' 'BADIKAHA' 'BAGOHOUO' 'BAHOMPA' 'BACOUBLY' 'BALEKO'
 'SAN-PEDRO' 'BANADJE' 'BANANKORO' 'BANDAKANY' 'BANDIAHI' 'BANGOLO'
 'BANIA' 'BANTEAPLEU' 'BAOUBLI' 'YAMOUSSOUKRO' 'GRAND-BASSAM' 'BAYOTA'
 'BAZRA NATTIS' 'BECEDIBRIGNAN' 'BEDIALA' 'BEKOUEFIN' 'BENGASSOU' 'BEOUE'
 'BEOUMI' 'BETTIE' 'BIANKOUMA' 'BIANOUAN' 'BIELOU-CARREFOUR' 'BILIMONO'
 'BINAO' 'BIN HOUNIEN' 'BLAHOU' 'BLANFLA' 'DIANOUFLA' 'BLE' 'BLESSEGUE'
 'BLOLEQUIN' 'BOCANDA' 'BODO' 'BODOKRO' 'BOGUEDIA' 'BOLI' 'BONAHOUIN'
 'BONDOUKOU' 'BONGO' 'BONGUERA' 'BONIEREDOUGOU' 'BONIKRO' 'BONON' 'BONOUA'
 'BONOUFLA' 'BOOKO' 'BORON' 'BOROTOU' 'BOROTOUKRO' 'BOTRO' 'BOUADIKRO'
 'BOUAFLE' 'BOUADOUGOU' 'BOUAPE' 'BOUGOU' 'BOUNA' 'BOUNAFLA' 'BOUNDIALI'
 'BOZI' 'BROBO' 'BROFFOUEDOU' 'BROFODOUME' 'BROU AKPASSOU' 'BUYO' 'CECHI'
 'CHIEPO' 'TREICHVILLE' 'COLLINEKASSEREGUE' 'KETEKRE' 'DABADOUGOU'
 'DABAKALA' 'DABOU' 'DABOUYO' 'DAGADJI' 'DAGOUAHIO' 'DAHIRI'
 'DAIRO/DIDIZO' 'DAKPADOU' 'DAME' 'DANANE' 'DANANON' 'DANGUIRA' 'DANIA'
 'DAOUKRO' 'DASSIOKO' 'DIABO' 'DIAMARAKRO' 'DIANGOKRO' 'DIANRA'
 'DIANRAVILLAGE' 'DIARABANA' 'DIARAKRO' 'DIAWALA' 'DIDIEVI' 'DIDOKO'
 'DIEGONEFLA' 'DIEOUZON' 'DIGNAGO' 'DIKODOUGOU' 'DIMBOKRO'
 'DIOULATIEDOUGOU' 'DIVO' 'DIVO PALMCI' 'DJASSANOU' 'DJEBONOUA'
 'DJEMISSIKRO' 'DJENIDOUFLA' 'DJIBROSSO' 'DJI' 'DJOUKOUYO' 'DOKE' 'DOROPO'
 'DOTENZIA' 'DOUFREBO' 'DOUGOUDOU SODEMI' 'DOUGROUPALEGNOA' 'DUEKOUE'
 'EBIKRO' 'EHANIA' 'ELLIBOU' 'HIRE' 'ETTROKRO' 'ETUEBOUE' 'FACOBLY'
 'FADYADOUGOU' 'FEREDOUGOU' 'FERKE' 'FLAKIE' 'FOUMBOLO' 'FOUNGBESSO'
 'FRESCO' 'FRONAN' 'GABIADJI' 'GADOUAN' 'GAGNOA' 'GAZIBOUO' 'GBAGBAM'
 'GBAPLEU' 'GRAND BEREBY' 'GBELEBAN' 'GBETEGUELA' 'GBONNE' 'GRAND LAHOU'
 'GLIGBEUADJI' 'GNABOYA' 'GNAGBODOUGNOA' 'GNAMONO' 'GNIPI' 'GOHITAFLA'
 'GOMENEBERI' 'GONATE' 'GOULIA' 'GRAND-ZATRY' 'GROBIASSOUME' 'GUEHIEBLY'
 'GUESSABO' 'GUESSIGUIE' 'GUEYO' 'GUEZON' 'GUEZON TAHOUAKE' 'GUIBEROUA'
 'GUIEMBE' 'GUIGLO' 'GUINKIN' 'GUINTEGUELA' 'GUITRY' 'HEREMANKONO'
 'HERMANKONONO/DIES' 'IBOGUHE' 'IDEFOR' 'ILESBOULEY' 'IROBO' 'ISSIA'
 'ITTY' 'JACQUEVILLE' 'KAHANSO' 'KAKOHORO' 'KALAKALA' 'KAMELE' 'KAMORO'
 'KANAKONO' 'KANI' 'KANOROBA' 'KANZRA' 'KASSERE' 'KATIOLA' 'KEIBLA'
 'KETESSO' 'KETRO BASSAM' 'KIMBIRILA NORD' 'KIMBIRILA SUD' 'KLOTOU'
 'KOBEDAIGOURE' 'KODIOSSOU' 'KODJINAN' 'KOFFI AMONKRO' 'KOKOUMBO' 'KOLIA'
 'KOMBORODOUGOU' 'KONAHIRI' 'KONEDOUGOU' 'KONG' 'KONGASSO' 'KONI'
 'KONONFLA' 'KONTROU' 'KOONAN' 'KOREA' 'KORHOGO' 'KORO' 'KOSSANDJI'
 'KOSSOU' 'KOTABLEA' 'KOTOUBA' 'KOTOULA' 'KOUASSIDATEKRO'
 'KOUASSIKOUASSIKRO' 'KOUEGO' 'KOUIBLY' 'KOUN-FAO' 'KOUNTIGUISSO' 'KOUTO'
 'KOYOKRO' 'KPAPEKOU' 'KPOUEBO' 'KRINJABO' 'KRIZABAHIO' 'LAFOKPOKAHA'
 'DEDI' 'LAHOUDIBA' 'LAKOTA' 'LAMADOUGOU' 'LAOGUIE' 'LARABIA' 'LATAHA'
 'LUEHOUAN' 'LOGBOVILLE' 'LOGOUALE' 'LOUGBONON' 'LOVIGUE' 'LUENOUFLA'
 'MADINANI' 'MAFERE' 'MAHAPLEU' 'MAMA' 'MAN' 'MANKONO' 'MANZANOUAN'
 'MARABADIASSA' 'MARANDALA' 'MASSALA' 'MAYO' "M'BAHIAKRO" 'MBATTO'
 'MBENGUE' 'MBONOUA' 'MBORLA' 'MBROU' 'MEADJI' 'MEMNI' 'MINIGNAN' 'MINORE'
 'MOAPE' 'MONTCOUPE' 'MORONDO' 'MORONOU' 'MOUSSADOUGOU' 'NAFALA' 'NAMASSI'
 'NAMBENGUE' 'KARAKORO' 'NANIEFONGO' 'NAPIE' 'NASSIAN' 'KOUASSIA-NIAGUNI'
 "N'DEBO" "N'DOUCI" 'NDOUKAHAKRO' 'NEKA' 'NGATTADOLIKRO' "N'GATTAKRO"
 'NGUINOU' 'NIABABLY' 'NIABLE' 'NIAKARA' 'TOUIH' 'NIAMANA' 'NIAMBEZARIA'
 'NIANDA' 'NIANGBO' 'NIDROU' 'NIOFOIN' 'NOE' 'NOUAMOU' 'NOUKPOUDOU'
 'NOUVELLEOUSROU' "N'ZECREZESSOU" 'NZIANOUA' "N'ZIKRO" 'ODIENNE' 'OGHLAPO'
 'OKROUYO' 'ORESS KROBOU' 'OTTAWA' 'OUALEBO' 'OUANGOLO' 'OUANINOU'
 'OUATTARADOUGOU' 'OUELLE' 'OUME' 'OUNADIEKAHA' 'OUPOYO' 'OURAGAHIO'
 'PAKAOUBO' 'BLIDOUBA' 'IBOKE' 'PARA' 'PEHE' 'PELEZI' 'PETIONARA'
 'PETIT YAPO' 'PINHOU' 'PINHOU KOULOUAN' 'PODIAGOUINE' 'POGO'
 'PONANGUIGLO' 'PRIKRO' 'POPREAGUI' 'SIPILOU' 'RAPIDES GRAH' 'RAVIART'
 'RUBINO' 'SAFCO' 'SAGO' 'SAHUE' 'SAIOUA' 'SAKAHOUO' 'SAKASSOU' 'SAMANGO'
 'SAMATIGUILA' 'SAMO' 'SANANFEREDOUGOU' 'SANDEGUE' 'SANGOUINE'
 'SANKADIOKRO' 'SAPLI' 'SARAKADJI' 'SARHALA' 'SASSANDRA' 'SATIKRAN'
 'SEGUELA' 'SEGUELON' 'SEMIEN' 'SERHIO' 'SEYDOUGOU' 'GOUMERE' 'SIANA'
 'SIEMPURGO' 'SIENSOBA' 'SIFIE' 'SIKENSI' 'SINEMATIALI' 'SINFRA'
 'SINGROBO' 'SIRASSO' 'MOUSSAYO' 'SOKORODOUGOU' 'SOMINANSE' 'SONDO'
 'SONGON' 'SONGON DAGBE' 'SONONZO' 'SOROBANGO' 'SOUBRE' 'BALEYO'
 'ZUENOULA' 'TAABO' 'TABAGNE' 'TABOU' 'TAFIRE' 'TAHIRAGUHE' 'TAHOGORA'
 'TAI' 'TALA' 'TANDI' 'TANDA' 'TANGUELAN' 'TANKESSE' 'TAOUDI'
 'TINDENE BAMBARASSO' 'TENGRELA' 'TIAPOUM' 'TIASSALE' 'TIEBISSOU' 'TIEMA'
 'TIEMELEKRO' 'TIEME' 'TIENDEKRO' 'TIENKO' 'TIMBE' 'TIOBLY' 'TOROGUHE'
 'TORO-KINKENE' 'TORTYA' 'TOUBA' 'TOUKOUZOU' 'TOULEUPLEU' 'TOUMODI'
 'DJEKANOU' 'TOUMODISAKASSOU' 'TOUPAH' 'TOUVRE' 'TRANSUA' 'VAVOUA'
 'VROUHO' 'WENDENE' 'WOROFLA' 'YABAYO' 'YAKASSE-ATTOBROU' 'YAKASSEFEYASSE'
 'YAKASSEME' 'YAOKRO' 'YAOSEDOUGOU' 'YAOU' 'YOROBODI' 'YOUWASSO' 'ZAALA'
 'ZADDI' 'ZAGNE' 'ZAIBO' 'ZALIOHOUAN' 'ZAMBAKRO' 'ZARANOU' 'ZAROKO'
 'ZATTA' 'ZIKISSO' 'ZON-HOUNIEN' 'ZOUKOUGBEU']
['In Service' nan]
['ABIDJAN' 'INTERIEUR']
['"Abidjan_EST' 'Grand-EST' 'Grand-OUEST' '"Abidjan_NORD'
 '"Abidjan_CENTRE' 'Abidjan_NORD' 'Abidjan_EST' 'Abidjan_OUEST'
 'Grand-SUD' 'SUD-OUEST' 'Abidjan_CENTRE' 'Abidjan_SUD' 'Grand-NORD'
 'Gd-ABIDJAN' '0']
['AGBANNEW' 'ASSINIE"' 'KRIKOREA"' 'NPONON' 'OKAHOTEL' 'PALMABINGERVILLE'
 'TIAMA' 'WILLIAMSVILLE2' 'ZONE E - Abidjan_NORD' 'ZONE B - Abidjan_EST'
 'ZONE D - Grand-OUEST' 'ZONE C - Grand-EST' 'ZONE C - Abidjan_OUEST'
 'ZONE B - Grand-SUD' 'ZONE E - SUD-OUEST' 'ZONE A - Abidjan_CENTRE'
 'ZONE B - Abidjan_OUEST' 'ZONE B - Abidjan_CENTRE' 'ZONE D - Abidjan_SUD'
 'ZONE B - Grand-EST' 'ZONE A - Grand-NORD' 'ZONE D - Grand-SUD'
 'ZONE D - Abidjan_EST' 'ZONE C - Grand-SUD' 'ZONE C - Abidjan_SUD'
 'ZONE A - Grand-SUD' 'ZONE C - Abidjan_EST' 'ZONE B - Abidjan_Nord' nan
 'ZONE A - Grand-EST' 'ZONE B - Abidjan-EST' 'ZONE A - Abidjan_OUEST'
 'ZONE B - Abidjan_SUD' 'ZONE B - Grand-NORD']
[-4.00066667 -3.48846667 -6.62705556 ... -4.01794444 -6.03969444
 -6.06545   ]
[5.36819444 5.15876111 6.70736111 ... 5.26519444 7.42861111 7.44459167]
['LAGUNE' 'SUD COMOE' 'HAUT SASSANDRA' 'MOYEN COMOE' 'AGNEBY'
 'SUD BANDAMA' 'BAS SASSANDRA' 'LACS' 'FROMAGER' 'VALLEE DU BANDAMA'
 'NZI COMOE' 'ZANZAN' 'MOYEN CAVALLY' 'WORODOUGOU' 'DENGUELE'
 '18 MONTAGNES' 'SAVANE' 'MARAHOUE' 'BAFING']
[nan 'ABIDJAN NORTH' 'NORTH WEST' 'EAST' 'ABIDJAN SOUTH' 'SOUTH WEST'
 'CENTRE NORTH']
['1502501d78' '0c2e182a0c' '69bdfc69fd' ... 'cb71f8a29c' 'd4a6a0b645'
 'f9f3e42589']
['0bb492ef17' '8a1e6ce31f' '260dbfedc5' ... '6daf54117b' 'f91ed8d2e9'
 '61bee9c70c']

#1.2.2.Finding unique values in cells geo description

In [ ]:
#Printing unique values in each column
print(df2.Description.unique())
print(df2.Format.unique())

['City' 'In Service or not' 'in ABIDJAN or not' 'Geographical Zone'
 'Name of Zone' 'Longitude' 'Latitude' 'Region' 'Area' 'ID of the cell'
 'Site (there are several cells per site, several sites per City, several Cities per Zone, etc.)']
['String' 'Float']

#1.2.3.Unique values in CDR description

In [ ]:
#Unique values in the columns
print(df2.Description.unique())
print(df2.Format.unique())

['City' 'In Service or not' 'in ABIDJAN or not' 'Geographical Zone'
 'Name of Zone' 'Longitude' 'Latitude' 'Region' 'Area' 'ID of the cell'
 'Site (there are several cells per site, several sites per City, several Cities per Zone, etc.)']
['String' 'Float']

#1.2.4.Unique values in moringa dataset1

In [ ]:
#Finding unique values in the columns of moringa dataset1
print(df4.PRODUCT.unique())
print(df4.VALUE.unique())
print(df4.DATE_TIME.unique())
print(df4.CELL_ON_SITE.unique())
print(df4.DW_A_NUMBER.unique())
print(df4.DW_B_NUMBER.unique())
print(df4.COUNTRTY_A.unique())
print(df4.COUNTRY_B.unique())
print(df4.CELL_ID.unique())
print(df4.SITE_ID.unique())

['Voice' 'data' 'sms']
[  53   63    0 ... 3494 1811 1006]
['2012-05-07 06:48:00.0' '2012-05-07 06:48:01.0' '2012-05-07 06:48:02.0'
 ... '2012-05-07 10:21:45.0' '2012-05-07 10:21:46.0' '2012-']
['1' '3' '0' '2' '5' '_' '4' '7' '6' '8' '9' 'C' 'A' 'F' 'B' 'D' 'E' nan]
['cc1c2c247d90f20' 'da71d8c96aa1d6b' '88505e894f3329c' ...
 'e066b10bbdfcca0' '15e4c710ca93698' nan]
['693cfdaf2faecfc' '321c4d54897ed92' '6e877e39823c5e2' ...
 'e4e1880978db4ba' 'df3aa213c1e13d1' nan]
['19e2e' 'OTHER' nan]
['19e2e' 'OTHER' nan]
['c258ffa6f0' '9c4c7ceb92' 'e38ca1003e' ... '6f8bfedb32' '9f74993cc7' nan]
['f72cd95f00' 'a07e8af2b4' '947b96a9ae' ... 'a0415ee50f' 'b941f9d7f6'
 'b1cb361ff1']

#1.2.5.Unique values in moringa dataset2

In [ ]:
#Finding unique values in the columns of moringa dataset1
print(df5.PRODUCT.unique())
print(df5.VALUE.unique())
print(df5.DATE_TIME.unique())
print(df5.CELL_ON_SITE.unique())
print(df5.DW_A_NUMBER.unique())
print(df5.DW_B_NUMBER.unique())
print(df5.COUNTRTY_A.unique())
print(df5.COUNTRY_B.unique())
print(df5.CELL_ID.unique())
print(df5.SITE_ID.unique())

['sms' 'Voice' 'data']
[   0   37   25 ... 2342 2927 3840]
['2012-05-07 23:02:06.0' '2012-05-07 23:03:44.0' '2012-05-07 23:04:06.0'
 ... '2012-05-09 00:58:02.0' '2012-05-09 00:58:14.0'
 '2012-05-09 00:59:05.0']
['2' '1' '0' '4' '_' '3' '5' '8' '7' '6' '9' 'E' 'F' 'B' 'C' 'D' 'A']
['32255675c3b6fe3' 'ff16d6ac74c1c64' '98d9f2fb5ff624b' ...
 '4d13e473756e02c' 'f7d808ebf1811fd' '5b77bb60924847f']
['1aa7ae01386e9fb' '87d87309c15a8c9' '93343ba6e41af95' ...
 'b767e7ffdc914b9' 'c3fe9ff651c129d' '4787949cbbb4e0c']
['19e2e' 'OTHER']
['19e2e' 'OTHER']
['+854AcBQT2' '+laSrk7g6q' '/xvRrCVKoQ' ... '578265bd12' '2def69183e'
 'b6d0b5d998']
['+854AcBQT2' '+laSrk7g6q' '/xvRrCVKoQ' ... 'd5307ec2ab' '7fcf74fb46'
 'd5b3d9a8a0']

#1.2.6.Unique values in moringa dataset 3

In [ ]:
print(df6.PRODUCT.unique())
print(df6.VALUE.unique())
print(df6.DATE_TIME.unique())
print(df6.CELL_ON_SITE.unique())
print(df6.DW_A_NUMBER.unique())
print(df6.DW_B_NUMBER.unique())
print(df6.COUNTRTY_A.unique())
print(df6.COUNTRY_B.unique())
print(df6.CELL_ID.unique())
print(df6.SITE_ID.unique())

['Voice' 'sms' 'data']
[  61    0   10 ... 1538 1347 1832]
['2012-05-08 23:01:28.0' '2012-05-08 23:01:31.0' '2012-05-08 23:02:59.0'
 ... '2012-05-09 10:52:57.0' '2012-05-09 10:52:58.0'
 '2012-05-09 10:52:59.0']
['2' '1' '0' '4' '_' '5' '3' '6' '7' '8' 'E' 'F' 'A' 'B' '9' 'C' 'D']
['966f68353622feb' 'a0a597384c612d7' '5441a9a58c97132' ...
 'a1ed5e9b580566b' '7f3f1434b48b97a' '1151bc079c3']
['ffd53a3bb2db6f1' 'cf3b218f1dde792' '52f8b299515b9b7' ...
 '0fa2bfd6462164f' '2cba4405b66cb71' nan]
['19e2e' 'OTHER' nan]
['19e2e' 'OTHER' nan]
['+38u2u/rfx' '+Fs4mTvdKx' '+ZaaZozy/+' ... 'd0f9ad8cd4' '6f90659c13' nan]
['+38u2u/rfx' '+Fs4mTvdKx' '+ZaaZozy/+' ... '5cea0b9078' '3b3a4de074'
 '0a168153cb']

#1.3.Data cleaning

In [10]:
#combining cells geo description and cdr  description dataset
df7 = pd.concat([df2,df3], axis=0)
df7

        Column name                                        Description   Format
0            VILLES                                               City   String
1            STATUS                                  In Service or not   String
2      LOCALISATION                                  in ABIDJAN or not   String
3        DECOUPZONE                                  Geographical Zone   String
4          ZONENAME                                       Name of Zone   String
5         LONGITUDE                                          Longitude    Float
6          LATITUDE                                           Latitude    Float
7            REGION                                             Region   String
8              AREA                                               Area   String
9           CELL_ID                                     ID of the cell   String
10        SITE_CODE  Site (there are several cells per site, severa...   String
0           PRODUCT                                       Voice or SMS   String
1             VALUE                                      Billing price  Integer
2         DATE_TIME               Time in format yyyy-MM-dd hh:mm:ss.0   String
3      CELL_ON_SITE  Which cell in the site was used (not needed here)  Integer
4   DW_A_NUMBER_INT  Anonymized phone number of the person for whic...   String
5   DW_B_NUMBER_INT        Anonymized phone number of the counterparty   String
6         COUNTRY_A                  Country of party A (useless here)   String
7         COUNTRY_B                  Country of party B (useless here)   String
8           CELL_ID                                     ID of the cell   String
9           SITE_ID                                     ID of the SITE   String

In [ ]:
#Replacing NaN values with "."
import numpy as np
df1['Area'] = df1['Area'].replace(np.NaN, ".")
df1

          City      Status   Locality  ...          Area     Cell_ID     Site_ID
1       ADJAME  In Service    ABIDJAN  ...             .  1502501d78  0bb492ef17
2       ADJAME  In Service    ABIDJAN  ...             .  0c2e182a0c  0bb492ef17
3      ASSINIE  In Service  INTERIEUR  ...             .  69bdfc69fd  8a1e6ce31f
4      ASSINIE  In Service  INTERIEUR  ...             .  7a1029d2ab  8a1e6ce31f
5      ASSINIE  In Service  INTERIEUR  ...             .  0b4f56438f  8a1e6ce31f
...        ...         ...        ...  ...           ...         ...         ...
3969  ZUENOULA  In Service  INTERIEUR  ...  CENTRE NORTH  1cfc2d7ab1  f91ed8d2e9
3970  ZUENOULA  In Service  INTERIEUR  ...  CENTRE NORTH  3ae1708153  f91ed8d2e9
3971  ZUENOULA  In Service  INTERIEUR  ...  CENTRE NORTH  cb71f8a29c  61bee9c70c
3972  ZUENOULA  In Service  INTERIEUR  ...  CENTRE NORTH  d4a6a0b645  61bee9c70c
3973  ZUENOULA  In Service  INTERIEUR  ...  CENTRE NORTH  f9f3e42589  61bee9c70c

[3973 rows x 11 columns]

In [ ]:
#Checking if there are any duplicates in our data
print(df1.duplicated())
print(df4.duplicated())
print(df7.duplicated())

1       False
2       False
3       False
4       False
5       False
        ...
3969    False
3970    False
3971    False
3972    False
3973    False
Length: 3973, dtype: bool
0          False
1          False
2          False
3          False
4          False
           ...
3052915    False
3052916    False
3052917    False
3052918    False
3052919    False
Length: 3052920, dtype: bool
0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8      True
9     False
dtype: bool

In [ ]:
#Dropping duplicates in our merged dataset which was found to have duplicates.
df7.drop_duplicates()

        Column name                                        Description   Format
0            VILLES                                               City   String
1            STATUS                                  In Service or not   String
2      LOCALISATION                                  in ABIDJAN or not   String
3        DECOUPZONE                                  Geographical Zone   String
4          ZONENAME                                       Name of Zone   String
5         LONGITUDE                                          Longitude    Float
6          LATITUDE                                           Latitude    Float
7            REGION                                             Region   String
8              AREA                                               Area   String
9           CELL_ID                                     ID of the cell   String
10        SITE_CODE  Site (there are several cells per site, severa...   String
0           PRODUCT                                       Voice or SMS   String
1             VALUE                                      Billing price  Integer
2         DATE_TIME               Time in format yyyy-MM-dd hh:mm:ss.0   String
3      CELL_ON_SITE  Which cell in the site was used (not needed here)  Integer
4   DW_A_NUMBER_INT  Anonymized phone number of the person for whic...   String
5   DW_B_NUMBER_INT        Anonymized phone number of the counterparty   String
6         COUNTRY_A                  Country of party A (useless here)   String
7         COUNTRY_B                  Country of party B (useless here)   String
9           SITE_ID                                     ID of the SITE   String

In [12]:
import pandas as pd
#merging moringa datasets
df8 = pd.concat([df4,df5,df6], axis=0)
df8
#Dropping unwanted columns
df8.drop(['COUNTRTY_A', 'COUNTRY_B'], axis=1)

        PRODUCT  VALUE  ...     CELL_ID     SITE_ID
0         Voice     53  ...  c258ffa6f0  f72cd95f00
1         Voice     63  ...  9c4c7ceb92  a07e8af2b4
2         Voice      0  ...  e38ca1003e  947b96a9ae
3         Voice      0  ...  73ebcb5c68  f078b9eea8
4         Voice    210  ...  96593c24dd  334fdb9912
...         ...    ...  ...         ...         ...
3686482     sms      0  ...  350ba627d1  71e0db3bff
3686483     sms      0  ...  3516a6737a  2401a3c831
3686484     sms      0  ...  104e2f7154  165d822fcb
3686485     sms      0  ...  8c02a28508  f9c46f6693
3686486     sms      0  ...         NaN         NaN

[26345519 rows x 8 columns]

#1.4.Data Analysis

#1.4.1.Which ones were the most used product for the three days?

In [13]:
df8.groupby('PRODUCT').sum()

             VALUE
PRODUCT
Voice    829637675
data       3694425
sms       16881387

#Which were the most used site during business and home hours?

In [27]:
sd = df8.groupby('SITE_ID')['VALUE'].sum()
sd

SITE_ID
++ctND+jGD    17468
+38u2u/rfx    19758
+854AcBQT2    16880
+Fs4mTvdKx    19261
+QZ9qRtNxA    16193
              ...
zn4qbCp2XH    16912
zqHx55Evcc    15028
zsA2dnzCR5    16422
zyYNfma31d    13192
zygULWQ6ny    13945
Name: VALUE, Length: 3179, dtype: int64

#describing the dataset

In [13]:
print(df1.describe())
#
print(df7.describe())
print(df8.describe())

         Longitude     Latitude
count  3973.000000  3973.000000
mean     -4.877880     6.244970
std       1.300861     1.304289
min      -8.503889     0.000000
25%      -5.846139     5.338639
50%      -4.084500     5.475000
75%      -3.993444     6.872306
max      -0.000000    10.481861
       Column name     Description  Format
count           21              21      21
unique          20              20       3
top        CELL_ID  ID of the cell  String
freq             2               2      17
              VALUE
count  2.634552e+07
mean   3.227165e+01
std    8.063318e+01
min    0.000000e+00
25%    0.000000e+00
50%    0.000000e+00
75%    3.800000e+01
max    3.487000e+04